version: '3'
services:
  redis:
    image: 'redis:latest'
    container_name: 'my-redis'
    ports:
      - '6379:6379'
    environment:
    - REDIS_PASSWORD=${REDIS_PASSWORD}

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./publisher:/app
    depends_on:
      - redis
    env_file: .env

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./subscriber:/app
    depends_on:
      - redis
    env_file: .env


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

volumes:
  redis-data:
